#!/usr/bin/ruby

if File.exists?(File.join(File.expand_path('../..', __FILE__), '.git'))
  lib_path = File.expand_path('../../lib', __FILE__)
  $:.unshift(lib_path)
end

require 'rubygems'
require '<%= args[0] %>'
require '<%= args[0] %>/cli'

<%= args[0].classify %>::CLI.start
